spring:

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms

  datasource:
    # 因为Spring Boot 2.1.x默认使用了MySQL 8.0的驱动，所以这里采用com.mysql.cj.jdbc.Driver，而不是老的com.mysql.jdbc.Driver。
    # 这一项可配可不配，如果不配置druid会根据url自动识别dbType，然后选择相应的driverClassName。
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/gui_guang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

    druid:
      # druid 链接池配置

      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时。
      # 默认值：0
      initial-size: 10
      # 最大连接池数量
      # 默认值：8
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒。
      # 配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 60000
      # 最小连接池数量
      min-idle: 1
      # 有两个含义：
      # 1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      # 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明。
      # 默认值：1分钟（1.0.14）
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 建议配置为true，不影响性能，并且保证安全性。
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      # 默认值：false
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      # 默认值：true
      test-on-borrow: true
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      # 默认值：false
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      # 默认值：false
      pool-prepared-statements: true
      # 缓存PreparedStatement的最大数量。大于0时会自动开启缓存PoolPreparedStatement，所以可以省略上一句代码。
      # 默认-1（不缓存）
      max-open-prepared-statements: 20
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: SELECT 1
      # 单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
      validation-query-timeout: 500
      # 属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有： 监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      # 配置了wall值，durid会监控到对表访问维度、SQL防御维度的统计。
      filters: stat, wall

      # druid 监控配置
      stat-view-servlet:
        # 是否开启监控
        enabled: true
        # 访问地址规则 http://localhost:8080/druid/
        url-pattern: /druid/*
        # 是否允许清空统计数据
        reset-enable: true
        login-username: admin
        login-password: admin




mybatis:
  mapper-locations: classpath:/mapper/*.xml
  # type-aliases-package: com.y.gui.dao
  # mybatis打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


